project:
  type: website
website:
  title: "hypertidy-blog"
  site-url: https://hypertidy.org
  description: "Geospatial data, GDAL, and R â€” Michael Sumner"
  repo-url: https://github.com/mdsumner/quarto-blog
  open-graph: true
  twitter-card:
    creator: "@mdsumner"
    card-style: summary_large_image
  search: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mdsumner
      - icon: mastodon
        href: https://rstats.me/@mdsumner
      - icon: rss
        href: index.xml
format:
  html:
    theme: litera
    css: styles.css
execute:
  freeze: true
